package util

var words = map[string]string{
	// todo order by frequency to have a higher chance of reaching the key earlier in a loop
	"create":          "CREATE",
	"or":              "OR",
	"replace":         "REPLACE",
	"distributed":     "DISTRIBUTED",
	"query":           "QUERY",
	"for":             "FOR",
	"graph":           "GRAPH",
	"syntax":          "SYNTAX",
	"interpret":       "INTERPRET",
	"v2":              "V2",
	"typedef":         "TYPEDEF",
	"tuple":           "TUPLE",
	"break":           "BREAK",
	"continue":        "CONTINUE",
	"any":             "ANY",
	"union":           "UNION",
	"intersect":       "INTERSECT",
	"minus":           "MINUS",
	"select":          "SELECT",
	"from":            "FROM",
	"where":           "WHERE",
	"accum":           "ACCUM",
	"if":              "IF",
	"then":            "THEN",
	"else":            "ELSE",
	"end":             "END",
	"case":            "CASE",
	"when":            "WHEN",
	"while":           "WHILE",
	"limit":           "LIMIT",
	"do":              "DO",
	"foreach":         "FOREACH",
	"in":              "IN",
	"range":           "RANGE",
	"step":            "STEP",
	"post-accum":      "POST-ACCUM",
	"offset":          "OFFSET",
	"install":         "INSTALL",
	"sumaccum":        "SumAccum",
	"int":             "INT",
	"float":           "FLOAT",
	"double":          "DOUBLE",
	"string":          "STRING",
	"maxaccum":        "MaxAccum",
	"minaccum":        "MinAccum",
	"avgaccum":        "AvgAccum",
	"oraccum":         "OrAccum",
	"andaccum":        "AndAccum",
	"bitwiseoraccum":  "BitwiseorAccum",
	"bitwiseandaccum": "BitwiseandAccum",
	"listaccum":       "ListAccum",
	"setaccum":        "SetAccum",
	"set":             "SET",
	"bagaccum":        "BagAccum",
	"mapaccum":        "MapAccum",
	"heapaccum":       "HeapAccum",
	"asc":             "ASC",
	"desc":            "DESC",
	"groupbyaccum":    "GroupbyAccum",
	"arrayaccum":      "ArrayAccum",
	"filter":          "FILTER",
	"coalesce":        "COALESCE",
	"distinct":        "DISTINCT",
	"isempty":         "ISEMPTY",
	"not":             "NOT",
	"is":              "IS",
	"null":            "NULL",
	"between":         "BETWEEN",
	"and":             "AND",
	"true":            "TRUE",
	"false":           "FALSE",
	"like":            "LIKE",
	"count":           "COUNT",
	"max":             "MAX",
	"min":             "MIN",
	"avg":             "AVG",
	"sum":             "SUM",
	"print":           "PRINT",
	"to_csv":          "TO_CSV",
	"as":              "AS",
	"bool":            "BOOL",
	"uint":            "UINT",
	"vertex":          "VERTEX",
	"edge":            "EDGE",
	"jsonobject":      "JSONOBJECT",
	"jsonarray":       "JSONARRAY",
	"datetime":        "DATETIME",
	"gsql_uint_max":   "GSQL_UINT_MAX",
	"gsql_int_max":    "GSQL_INT_MAX",
	"gsql_uint_min":   "GSQL_UINT_MIN",
	// Types
	// "int"
}
var keywordRegexes = []string{
	`\b[cC][rR][eE][aA][tT][eE]\b`,
	`\b[cC][rR][eE][aA][tT][eE]\b`,
	`\b[oO][rR]\b`,
	`\b[rR][eE][pP][lL][aA][cC][eE]\b`,
	`\b[dD][iI][sS][tT][rR][iI][bB][uU][tT][eE][dD]\b`,
	`\b[qQ][uU][eE][rR][yY]\b`,
	`\b[fF][oO][rR]\b`,
	`\b[gG][rR][aA][pP][hH]\b`,
	`\b[sS][yY][nN][tT][aA][xX]\b`,
	`\b[iI][nN][tT][eE][rR][pP][rR][eE][tT]\b`,
	`\b[qQ][uU][eE][rR][yY]\b`,
	`\b[fF][oO][rR]\b`,
	`\b[gG][rR][aA][pP][hH]\b`,
	`\b[sS][yY][nN][tT][aA][xX]\b`,
	`\b[vV][22]\b`,
	`\b[sS][eE][tT]\b`,
	`\b[tT][yY][pP][eE][dD][eE][fF]\b`,
	`\b[tT][uU][pP][lL][eE]\b`,
	`\b[bB][rR][eE][aA][kK]\b`,
	`\b[cC][oO][nN][tT][iI][nN][uU][eE]\b`,
	`\b[aA][nN][yY]\b`,
	`\b[uU][nN][iI][oO][nN]\b`,
	`\b[iI][nN][tT][eE][rR][sS][eE][cC][tT]\b`,
	`\b[mM][iI][nN][uU][sS]\b`,
	`\b[sS][eE][lL][eE][cC][tT]\b`,
	`\b[fF][rR][oO][mM]\b`,
	`\b[wW][hH][eE][rR][eE]\b`,
	`\b[aA][cC][cC][uU][mM]\b`,
	`\b[bB][rR][eE][aA][kK]\b`,
	`\b[cC][oO][nN][tT][iI][nN][uU][eE]\b`,
	`\b[iI][fF]\b`,
	`\b[tT][hH][eE][nN]\b`,
	`\b[eE][lL][sS][eE]\b`,
	`\b[iI][fF]\b`,
	`\b[tT][hH][eE][nN]\b`,
	`\b[eE][lL][sS][eE]\b`,
	`\b[eE][nN][dD]\b`,
	`\b[cC][aA][sS][eE]\b`,
	`\b[wW][hH][eE][nN]\b`,
	`\b[tT][hH][eE][nN]\b`,
	`\b[eE][lL][sS][eE]\b`,
	`\b[eE][nN][dD]\b`,
	`\b[cC][aA][sS][eE]\b`,
	`\b[wW][hH][eE][nN]\b`,
	`\b[tT][hH][eE][nN]\b`,
	`\b[eE][lL][sS][eE]\b`,
	`\b[eE][nN][dD]\b`,
	`\b[wW][hH][iI][lL][eE]\b`,
	`\b[lL][iI][mM][iI][tT]\b`,
	`\b[dD][oO]\b`,
	`\b[eE][nN][dD]\b`,
	`\b[fF][oO][rR][eE][aA][cC][hH]\b`,
	`\b[dD][oO]\b`,
	`\b[eE][nN][dD]\b`,
	`\b[iI][nN]\b`,
	`\b[iI][nN]\b`,
	`\b[rR][aA][nN][gG][eE]\b`,
	`\b[sS][tT][eE][pP]\b`,
	`\b[pP][oO][sS][tT][--][aA][cC][cC][uU][mM]\b`,
	`\b[lL][iI][mM][iI][tT]\b`,
	`\b[oO][fF][fF][sS][eE][tT]\b`,
	`\b[aA][nN][yY]\b`,
	`\b[aA][nN][yY]\b`,
	`\b[cC][aA][sS][eE]\b`,
	`\b[wW][hH][eE][nN]\b`,
	`\b[tT][hH][eE][nN]\b`,
	`\b[eE][lL][sS][eE]\b`,
	`\b[eE][nN][dD]\b`,
	`\b[cC][aA][sS][eE]\b`,
	`\b[wW][hH][eE][nN]\b`,
	`\b[tT][hH][eE][nN]\b`,
	`\b[eE][lL][sS][eE]\b`,
	`\b[eE][nN][dD]\b`,
	`\b[iI][fF]\b`,
	`\b[tT][hH][eE][nN]\b`,
	`\b[eE][lL][sS][eE]\b`,
	`\b[iI][fF]\b`,
	`\b[tT][hH][eE][nN]\b`,
	`\b[eE][lL][sS][eE]\b`,
	`\b[eE][nN][dD]\b`,
	`\b[wW][hH][iI][lL][eE]\b`,
	`\b[lL][iI][mM][iI][tT]\b`,
	`\b[dD][oO]\b`,
	`\b[eE][nN][dD]\b`,
	`\b[fF][oO][rR][eE][aA][cC][hH]\b`,
	`\b[dD][oO]\b`,
	`\b[eE][nN][dD]\b`,
	`\b[iI][nN][sS][tT][aA][lL][lL]\b`,
	`\b[qQ][uU][eE][rR][yY]\b`,
	`\b[sS][uU][mM][aA][cC][cC][uU][mM]\b`,
	`\b[iI][nN][tT]\b`,
	`\b[fF][lL][oO][aA][tT]\b`,
	`\b[dD][oO][uU][bB][lL][eE]\b`,
	`\b[sS][tT][rR][iI][nN][gG]\b`,
	`\b[mM][aA][xX][aA][cC][cC][uU][mM]\b`,
	`\b[iI][nN][tT]\b`,
	`\b[fF][lL][oO][aA][tT]\b`,
	`\b[dD][oO][uU][bB][lL][eE]\b`,
	`\b[mM][iI][nN][aA][cC][cC][uU][mM]\b`,
	`\b[iI][nN][tT]\b`,
	`\b[fF][lL][oO][aA][tT]\b`,
	`\b[dD][oO][uU][bB][lL][eE]\b`,
	`\b[aA][vV][gG][aA][cC][cC][uU][mM]\b`,
	`\b[oO][rR][aA][cC][cC][uU][mM]\b`,
	`\b[aA][nN][dD][aA][cC][cC][uU][mM]\b`,
	`\b[bB][iI][tT][wW][iI][sS][eE][oO][rR][aA][cC][cC][uU][mM]\b`,
	`\b[bB][iI][tT][wW][iI][sS][eE][aA][nN][dD][aA][cC][cC][uU][mM]\b`,
	`\b[lL][iI][sS][tT][aA][cC][cC][uU][mM]\b`,
	`\b[lL][iI][sS][tT][aA][cC][cC][uU][mM]\b`,
	`\b[sS][eE][tT][aA][cC][cC][uU][mM]\b`,
	`\b[sS][eE][tT][aA][cC][cC][uU][mM]\b`,
	`\b[bB][aA][gG][aA][cC][cC][uU][mM]\b`,
	`\b[mM][aA][pP][aA][cC][cC][uU][mM]\b`,
	`\b[hH][eE][aA][pP][aA][cC][cC][uU][mM]\b`,
	`\b[aA][sS][cC]\b`,
	`\b[dD][eE][sS][cC]\b`,
	`\b[aA][sS][cC]\b`,
	`\b[dD][eE][sS][cC]\b`,
	`\b[gG][rR][oO][uU][pP][bB][yY][aA][cC][cC][uU][mM]\b`,
	`\b[aA][rR][rR][aA][yY][aA][cC][cC][uU][mM]\b`,
	`\b[fF][iI][lL][tT][eE][rR]\b`,
	`\b[cC][oO][aA][lL][eE][sS][cC][eE]\b`,
	`\b[dD][iI][sS][tT][iI][nN][cC][tT]\b`,
	`\b[iI][sS][eE][mM][pP][tT][yY]\b`,
	`\b[nN][oO][tT]\b`,
	`\b[iI][nN]\b`,
	`\b[iI][sS]\b`,
	`\b[nN][oO][tT]\b`,
	`\b[nN][uU][lL][lL]\b`,
	`\b[bB][eE][tT][wW][eE][eE][nN]\b`,
	`\b[aA][nN][dD]\b`,
	`\b[nN][oO][tT]\b`,
	`\b[aA][nN][dD]\b`,
	`\b[oO][rR]\b`,
	`\b[tT][rR][uU][eE]\b`,
	`\b[fF][aA][lL][sS][eE]\b`,
	`\b[nN][oO][tT]\b`,
	`\b[lL][iI][kK][eE]\b`,
	`\b[fF][iI][lL][tT][eE][rR]\b`,
	`\b[uU][nN][iI][oO][nN]\b`,
	`\b[iI][nN][tT][eE][rR][sS][eE][cC][tT]\b`,
	`\b[mM][iI][nN][uU][sS]\b`,
	`\b[cC][oO][uU][nN][tT]\b`,
	`\b[mM][aA][xX]\b`,
	`\b[mM][iI][nN]\b`,
	`\b[aA][vV][gG]\b`,
	`\b[sS][uU][mM]\b`,
	`\b[pP][rR][iI][nN][tT]\b`,
	`\b[wW][hH][eE][rR][eE]\b`,
	`\b[tT][oO][__][cC][sS][vV]\b`,
	`\b[aA][sS]\b`,
	`\b[aA][sS]\b`,
	`\b[bB][oO][oO][lL]\b`,
	`\b[iI][nN][tT]\b`,
	`\b[uU][iI][nN][tT]\b`,
	`\b[fF][lL][oO][aA][tT]\b`,
	`\b[dD][oO][uU][bB][lL][eE]\b`,
	`\b[sS][tT][rR][iI][nN][gG]\b`,
	`\b[vV][eE][rR][tT][eE][xX]\b`,
	`\b[eE][dD][gG][eE]\b`,
	`\b[jJ][sS][oO][nN][oO][bB][jJ][eE][cC][tT]\b`,
	`\b[jJ][sS][oO][nN][aA][rR][rR][aA][yY]\b`,
	`\b[dD][aA][tT][eE][tT][iI][mM][eE]\b`,
	`\b[tT][rR][uU][eE]\b`,
	`\b[fF][aA][lL][sS][eE]\b`,
	`\b[gG][sS][qQ][lL][__][uU][iI][nN][tT][__][mM][aA][xX]\b`,
	`\b[gG][sS][qQ][lL][__][iI][nN][tT][__][mM][aA][xX]\b`,
	`\b[gG][sS][qQ][lL][__][uU][iI][nN][tT][__][mM][iI][nN]\b`,
}
